import type { Metadata } from "next";
import Menu from "./components/menu";
import "./global-styles/reset.scss";
import { ProfileProvider } from "./context/modalContext";
import ProfileModal from "./components/modals/profile";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <ProfileProvider>
          <Menu />
          <ProfileModal />
          {children}
        </ProfileProvider>
      </body>
    </html>
  );
}
