import type { Metadata } from "next";
import Menu from "./components/menu";
import "./global-styles/reset.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <Menu />
        {children}
      </body>
    </html>
  );
}
